# Generated by Django 6.0.5 on 2026-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coreservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicestype', models.CharField(max_length=100)),
                ('serviceicon', models.CharField(max_length=100)),
                ('servciebtn', models.CharField(max_length=100)),
            ],
        ),
    ]
