# Generated by Django 6.0.5 on 2026-05-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreservices',
            old_name='servicestype',
            new_name='serviceavialablty',
        ),
        migrations.RemoveField(
            model_name='coreservices',
            name='servciebtn',
        ),
        migrations.AddField(
            model_name='coreservices',
            name='servicereg',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coreservices',
            name='servicetype',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
