# Generated by Django 6.0.5 on 2026-05-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_servicestype_coreservices_serviceavialablty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreservices',
            name='cardcolor',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
