# Generated by Django 6.0.5 on 2026-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_coreservices_btncolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreservices',
            name='targetservice',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
