# Generated by Django 6.0.5 on 2026-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_coreservices_targetservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreservices',
            name='serviceiconcolor',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coreservices',
            name='serviceiconsize',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
