# Generated by Django 6.0.5 on 2026-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_coreservices_serviceiconcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
