# Generated by Django 6.0.5 on 2026-05-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff'),
        ),
    ]
