# Generated by Django 6.0.5 on 2026-05-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contact_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
